CREATE DATABASE CloudPlanning;
GO

USE CloudPlanning;
GO


CREATE TABLE usuario(
	idUsuario INT PRIMARY KEY IDENTITY,
	email VARCHAR(50) NOT NULL UNIQUE,
	senha VARCHAR(70) NOT NULL
)
GO

CREATE TABLE empresa(
	idEmpresa INT PRIMARY KEY IDENTITY,
	idUsuario INT FOREIGN KEY REFERENCES usuario(idUsuario),
	CNPJ VARCHAR(14) NOT NULL UNIQUE,
	nomeFantasia VARCHAR(70) NOT NULL UNIQUE,
	telefone VARCHAR(14) NOT NULL UNIQUE
);
GO

CREATE TABLE usuarioComum(
	idUsuarioComum INT PRIMARY KEY IDENTITY,
	idUsuario INT FOREIGN KEY REFERENCES usuario(idUsuario),
	idEmpresa INT FOREIGN KEY REFERENCES empresa(IdEmpresa),
	nome VARCHAR (70),
	CPF VARCHAR (12) NOT NULL UNIQUE,
	DataNascimento DATE NOT NULL,
)
GO


CREATE TABLE EC2(
	idEC2 INT PRIMARY KEY IDENTITY,
	idVPC INT FOREIGN KEY REFERENCES VPC(idVPC),
	nome VARCHAR(50), 
	imagemComponente VARCHAR(70), 
	descricao VARCHAR(100),
	sistemaOperacional VARCHAR(20) NOT NULL,
	armazenamento INT NOT NULL,
	quantidadeProcessadores INT NOT NULL,
	RAM INT NOT NULL,
	subRede VARCHAR(20) NOT NULL,
	autoAssign BIT DEFAULT(0),
	nomeChave VARCHAR(50)
)
GO

CREATE TABLE VPC(
	idVPC INT PRIMARY KEY IDENTITY,
	nome VARCHAR(50), 
	imagemComponente VARCHAR(70), 
	descricao VARCHAR(100),
	subRede VARCHAR(20) NOT NULL,
	rota VARCHAR(20) NOT NULL,
	natGateway varchar(20) NOT NULL,
)
GO

CREATE TABLE diagrama(
	idDiagrama INT PRIMARY KEY IDENTITY,
	idEmpresa INT FOREIGN KEY REFERENCES empresa(idEmpresa),
	idEC2 INT FOREIGN KEY REFERENCES EC2(idEC2),
	nome VARCHAR(70) NOT NULL UNIQUE,
);
GO


